### ISSUE TITLE
java.lang.NoClassDefFoundError: jenkins/branch/MultiBranchProject

### ISSUE THREAD

**Issue by reubenfirmin** [jenkinsci/last-changes-plugin#77]
After updating plugins, on jenkins 2.204.2

java.lang.NoClassDefFoundError: jenkins/branch/MultiBranchProject
	at com.github.jenkins.lastchanges.LastChangesProjectAction$LastChangesActionFactory.createFor(LastChangesProjectAction.java:53)
	at com.github.jenkins.lastchanges.LastChangesProjectAction$LastChangesActionFactory.createFor(LastChangesProjectAction.java:47)
	at hudson.model.Actionable.createFor(Actionable.java:114)
	at hudson.model.Actionable.getActions(Actionable.java:139)
	at hudson.model.Job.getPermalinks(Job.java:1068)
	at hudson.model.Job.getDynamic(Job.java:856)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:454)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)

**Comment by rmpestano** [comment]
Hi @reubenfirmin, can you try with the attached plugin? just unzip and install on your Jenkins installation.
[last-changes.hpi.zip](https://github.com/jenkinsci/last-changes-plugin/files/4226536/last-changes.hpi.zip)

**Comment by rmpestano** [comment]
Fixed for the just released `v2.7.9`
